### ISSUE TITLE
How to use the XMeans?

### ISSUE THREAD

**Issue by Youngsam** [mynameisfiber/pyxmeans#11]
Hi, I tried to test the code, but I failed every time and got no clue to go further.

Since I see no usage examples anywhere, I have no choice but to ask here.

Here is what I did:

##############################################################3
In [1]: from pyxmeans import XMeans as xmeans
In [4]: data = np.array([[ 1.        ,  0.10407638,  0.65109568,  0.12847974],
   ...:        [ 0.10407638,  1.        ,  0.10487307,  0.47660156],
   ...:        [ 0.65109568,  0.10487307,  1.        ,  0.31618136],
   ...:        [ 0.12847974,  0.47660156,  0.31618136,  1.        ]])

In [7]: test = xmeans(2)
In [8]: test.fit(data)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/youngsam/<ipython-input-8-00660608022d> in <module>()
----> 1 test.fit(res)

/usr/local/lib/python2.7/dist-packages/pyxmeans/xmeans.pyc in fit(self, data)
     34         while self.kmax is None or k <= self.kmax:
     35             logging.info("Fitting with k=%d", k)
---> 36             self._model = self._fit(k, data, cluster_centers)
     37 
     38             centroid_distances = euclidean_distances(self._model.centroids, self._model.centroids)

/usr/local/lib/python2.7/dist-packages/pyxmeans/xmeans.pyc in _fit(self, k, data, centroids)
    144             n_samples = n_samples,
    145             **self._minibatch_args
--> 146         ).fit(data[:])
    147         return KMeansResult(model.labels_, model.cluster_centers_)

/usr/local/lib/python2.7/dist-packages/pyxmeans/mini_batch.pyc in fit(self, data)
    113             jobs = min(self.n_jobs, self.n_init)
    114             if jobs > 1:
--> 115                 self.cluster_centers_ = _minibatch.kmeanspp_multi(data, self.cluster_centers_, self.n_samples, self.n_init, jobs)
    116             else:
    117                 self.cluster_centers_ = _minibatch.kmeanspp(data, self.cluster_centers_, self.n_samples)

RuntimeError: n_samples must be smaller than the number of samples

**Comment by mynameisfiber** [comment]
So that's from a little bug that occurs when using small datasets.  The `sample_percent` parameter controls how much of the incoming data we use for each minibatch and it defaults to 0.2.  In your case of 4 data points, that results in the solver trying to use 0 datapoints which doesn't make sense (`n_samples` gets set [here](https://github.com/mynameisfiber/pyxmeans/blob/master/pyxmeans/xmeans.py#L139)).

Anyways, the solution is simply to set `sample_percent` to 1.0 when instantiating the xmeans object.  This'll only be an issue when using <5 data points.

**Comment by Youngsam** [comment]
mynameisfiber// Thanks for your nice feedback and the work.
