### ISSUE TITLE
cannot import name _minibatch

### ISSUE THREAD

**Issue by rzlee** [mynameisfiber/pyxmeans#5]
Hi, I am unable to run the pyxmeans benchmark after installation. It fails with this error:
```cannot import name _minibatch```

I'm using the anaconda distribution of python with Numpy 1.8.2 and compiling with gcc 4.9 on a mac. The package compiled and installed successfully, with some warnings generated.

**Comment by pliskowski** [comment]
@mynameisfiber I have the same problem. No errors during installation. Installed simply with python setup.py install.

**Comment by mynameisfiber** [comment]
This is probably happening because you are trying to import pyxmeans while inside of the pyxmeans directory.  Python will try to load the package in the current directory instead of looking for the installed version.

```
electron ~/projects:$ python -c 'import pyxmeans'
electron ~/projects:$ cd pyxmeans
electron ~/projects/pyxmeans:(master)$ python -c 'import pyxmeans'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyxmeans/__init__.py", line 1, in <module>
    from . import _minibatch
ImportError: cannot import name _minibatch
```

Please tell me if this is infact the problem!
