### ISSUE TITLE
confusion about bic calculation

### ISSUE THREAD

**Issue by porcobosso** [mynameisfiber/pyxmeans#9]
xmeans.py (line 119):
```python
t4 = (fRn - 1.0) / 2.0
```
why not
```python
t4 = (fRn - len(clusters)) / 2.0
```
according to the paper (3.2 BIC Scoring)

**Comment by mynameisfiber** [comment]
Hey @porcobosso... I'd love to give you an answer, but this code was written a while ago and to tell you the truth I just don't recall.  I did just run the benchmark with the proposed change and got better resulting clusters.  Care to make a pull request?

**Comment by eyaler** [comment]
its ok the way it is. there is a typo in the xmeans paper.
t4 is in a loop summing over all clusters so sum_n(Rn-1) = R-N

however, as explained here:  https://github.com/bobhancock/goxmeans/blob/master/doc/BIC_notes.pdf
i think there should be an additional factor num_dims in t4 as well as in the denominator of the variance. see eq 16 and 19 in paper. should i open a new issue for this?

**Comment by mynameisfiber** [comment]
@eyaler Good research!  It'd be great if you could open a new pull request for that.  I'll close this request due to inactivity and wait for yours... thanks!
